apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: hello-node
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: hello-node
    spec: 
      containers: 
        - 
          image: "gcr.io/virajtest-167408/hello-node:12.0"
          imagePullPolicy: Always
          name: hello-node
          ports: 
            - 
              containerPort: 8080
              name: hello-node
              protocol: TCP
