apiVersion: extensions/v1beta1
kind: Deployment
metadata:  
  name: hello-node  
spec:
  replicas:
  template:
    metadata:
      name:hello-node
    spec:
      containers:
      - image: gcr.io/cloud-solutions-images/hello-node:1.0.0
        imagePullPolicy: Always
        name: hello-node
        ports:
        - "containerPort:8080 protocol: TCP  name:hello-node"